parameters:
  prometheus:
    server:
      target:
        static:
          etcd:
            scheme: https
            tls_config:
              skip_verify: true
              ssl_dir: /opt/prometheus/config
              cert_name: prometheus-server.crt
              key_name: prometheus-server.key
